name: Sincronizar Conta Azul para Looker

on:
  schedule:
    - cron: '0 9 * * *' # Roda todo dia às 06:00 (Horário de Brasília)
  workflow_dispatch: # Adiciona o botão de "Play" manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do GitHub
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar bibliotecas
        run: |
          pip install pandas requests gspread oauth2client

      - name: Rodar Script de Sincronização
        env:
          # Aqui conectamos as credenciais que você já tem no Streamlit
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
          CONTA_AZUL_CLIENT_ID: ${{ secrets.CONTA_AZUL_CLIENT_ID }}
          CONTA_AZUL_CLIENT_SECRET: ${{ secrets.CONTA_AZUL_CLIENT_SECRET }}
        run: python app.py
